#!/usr/bin/python3
# autopkgtest check: - Boot with kdump-tools/makedumpfile installed and verify
#                      if the context is adequate for tests
#                    - Reboot to enable crashkernel= kernel parameter
# (C) 2016 Canonical Ltd.
# Author: Louis Bouchard <louis.bouchard@canonical.com>

import os
import subprocess


def pre_boot_check():
    '''Check that kdump-tools is installed and configured prior to reboot'''

    with open('/etc/default/kdump-tools', 'r') as config:
        conf = config.readlines()

    assert ('USE_KDUMP=1\n' in conf), "USE_KDUMP is not enabled"

    out = subprocess.check_output(['kdump-config', 'show'],
                                  universal_newlines=True)
    assert ('current state:    Not ready to kdump' in out), "kdump ready ???"

if __name__ == '__main__':
    if not os.getenv('ADT_REBOOT_MARK'):
        pre_boot_check()
        print('Rebooting...')
        subprocess.check_call(['/tmp/autopkgtest-reboot', 'enable-crashkernel'])
